os:
  - linux
  - osx

language: cpp
sudo: required

script:
  - cmake .
  - make -j2

compiler:
  - clang
  - gcc

addons:
  apt:
    packages: 
      - libsdl2-dev 
      - libsdl2-mixer-dev 
      - libsdl2-image-dev 
      - libglew-dev 
      - libglm-dev 
      - mesa-common-dev
  homebrew:
    packages: 
      - sdl2 
      - sdl2_mixer 
      - sdl2_image 
      - glew 
      - glm
    update: true
notifications:
  webhooks:
    - https://krake.one/travis-ci/402390990402355201/9O9q4_MrVt5-VI-XGU5GKndoCebPJyVyBaEbLjzDijN-hhcLI9SqyfNLpzLaq3QEESMV
